### ISSUE TITLE
io.jpower.kcp.netty.KcpException: State=-1 after update()

### ISSUE THREAD

**Issue by weicchan** [szhnet/kcp-netty#25]
一个必现的问题，KCP连通之后十多秒会报这个异常，然后断开连接。详细日志如下，请问该怎么处理？ 另外1.4.10版本相对于1.4.9版本修改了什么？
2021-04-28 18:25:46.532 12041-12676/com.vvv.testkcp W/System.err: io.jpower.kcp.netty.KcpException: State=-1 after update()
2021-04-28 18:25:46.533 12041-12676/com.vvv.testkcp W/System.err:     at io.jpower.kcp.netty.UkcpClientChannel.run(UkcpClientChannel.java:307)
2021-04-28 18:25:46.533 12041-12676/com.vvv.testkcp W/System.err:     at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
2021-04-28 18:25:46.533 12041-12676/com.vvv.testkcp W/System.err:     at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
2021-04-28 18:25:46.533 12041-12676/com.vvv.testkcp W/System.err:     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
2021-04-28 18:25:46.533 12041-12676/com.vvv.testkcp W/System.err:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
2021-04-28 18:25:46.534 12041-12676/com.vvv.testkcp W/System.err:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
2021-04-28 18:25:46.534 12041-12676/com.vvv.testkcp W/System.err:     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2021-04-28 18:25:46.534 12041-12676/com.vvv.testkcp W/System.err:     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2021-04-28 18:25:46.534 12041-12676/com.vvv.testkcp W/System.err:     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-04-28 18:25:46.534 12041-12676/com.vvv.testkcp W/System.err:     at java.lang.Thread.run(Thread.java:923)

**Comment by lixiandea** [comment]
我碰到一样的问题，希望作者能够解决一下

**Comment by szhnet** [comment]
state = -1 表示重传次数过多，超过了deadLink。
